name = "static-ang"
type = "webpack"
route = ''
zone_id = ''
account_id = '5be98de62231a2edaeed0241a263059a'
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-01"
[site]
bucket = "./dist/static-ang"
entry-point = "workers-site"
